# -*- coding: utf-8 -*-
"""WT_First_Exploration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_ZECiXCd8foz_HDYPAMY6hr10BYHLKu
"""

import os
print(os.listdir())
#Check which datasets we have uploaded in our colab session

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st
sns.set()

def zone_annual():
    df_Zon = pd.read_csv("data/ZonAnn.Ts+dSST.csv")
    st.write(df_Zon.head())

    df_Zon_plot1 = plt.figure(figsize = (10,7))
    sns.lineplot(x = "Year", y = "Glob", data = df_Zon, label = "Global")
    sns.lineplot(x = "Year", y = "NHem", data = df_Zon, label = "Northern Hemisphere")
    sns.lineplot(x = "Year", y = "SHem", data = df_Zon, label = "Southern Hemisphere")
    plt.xlabel("Year")
    plt.ylabel("Temperature (ºC change)")
    plt.title("Temperature anomalies")
    plt.legend();

    st.pyplot(df_Zon_plot1)

    df_Zon_plot2 = plt.figure(figsize = (10,7))
    sns.lineplot(x = "Year", y = "Glob", data = df_Zon[df_Zon["Year"]>=1990], label = "Global")
    sns.lineplot(x = "Year", y = "NHem", data = df_Zon[df_Zon["Year"]>=1990], label = "Northern Hemisphere")
    sns.lineplot(x = "Year", y = "SHem", data = df_Zon[df_Zon["Year"]>=1990], label = "Southern Hemisphere")
    plt.xlabel("Year")
    plt.ylabel("Temperature (ºC change)")
    plt.title("Temperature anomalies")
    plt.legend();

    st.pyplot(df_Zon_plot2)
